/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package superstring;

/**
 *
 * @author jogra6669
 */
public class superString1 extends javax.swing.JFrame {

    /**
     * Creates new form superString1
     */
    public superString1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleSuper = new javax.swing.JLabel();
        promptSuper1 = new javax.swing.JLabel();
        inputSuper1 = new javax.swing.JTextField();
        promptLength = new javax.swing.JButton();
        promptSuper2 = new javax.swing.JLabel();
        inputSuper2 = new javax.swing.JTextField();
        promptCaps = new javax.swing.JButton();
        promptSuper3 = new javax.swing.JLabel();
        inputSuper3 = new javax.swing.JTextField();
        prompt4th = new javax.swing.JButton();
        promptSuper4 = new javax.swing.JLabel();
        inputSuper5 = new javax.swing.JTextField();
        promptIdentical = new javax.swing.JButton();
        promptSuper5 = new javax.swing.JLabel();
        inputSuper6 = new javax.swing.JTextField();
        promtFound = new javax.swing.JButton();
        promptSuper6 = new javax.swing.JLabel();
        inputSuper8 = new javax.swing.JTextField();
        prompt4To6 = new javax.swing.JButton();
        line1 = new javax.swing.JLabel();
        line2 = new javax.swing.JLabel();
        line3 = new javax.swing.JLabel();
        line4 = new javax.swing.JLabel();
        line5 = new javax.swing.JLabel();
        line6 = new javax.swing.JLabel();
        promptSuper7 = new javax.swing.JLabel();
        inputSuper9 = new javax.swing.JTextField();
        promptA = new javax.swing.JButton();
        inputSuper4 = new javax.swing.JTextField();
        inputSuper7 = new javax.swing.JTextField();
        responseSuper1 = new javax.swing.JLabel();
        responseSuper2 = new javax.swing.JLabel();
        responseSuper3 = new javax.swing.JLabel();
        responseSuper4 = new javax.swing.JLabel();
        responseSuper5 = new javax.swing.JLabel();
        responseSuper6 = new javax.swing.JLabel();
        responseSuper7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleSuper.setFont(new java.awt.Font("BinnerDEE", 0, 24)); // NOI18N
        titleSuper.setForeground(new java.awt.Color(51, 51, 255));
        titleSuper.setText("Super String Software");

        promptSuper1.setText("Enter a string. The program will output the number of characters in the String:");

        inputSuper1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSuper1ActionPerformed(evt);
            }
        });

        promptLength.setText("Length");
        promptLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promptLengthActionPerformed(evt);
            }
        });

        promptSuper2.setText("Enter a string using lowercase letters. The program will output the String in all capital letters:");

        inputSuper2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSuper2ActionPerformed(evt);
            }
        });

        promptCaps.setText("All caps");
        promptCaps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promptCapsActionPerformed(evt);
            }
        });

        promptSuper3.setText("Enter a string. The program the character at the 4th spot:");

        inputSuper3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSuper3ActionPerformed(evt);
            }
        });

        prompt4th.setText("4th Spot");
        prompt4th.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prompt4thActionPerformed(evt);
            }
        });

        promptSuper4.setText("Enter two strings. The program will output whether or not they are identical: ");

        inputSuper5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSuper5ActionPerformed(evt);
            }
        });

        promptIdentical.setText("Identical?");
        promptIdentical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promptIdenticalActionPerformed(evt);
            }
        });

        promptSuper5.setText("Enter a string and a letter. The program will output whether or not the letter is found in the String: ");

        inputSuper6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSuper6ActionPerformed(evt);
            }
        });

        promtFound.setText("Letter found?");
        promtFound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promtFoundActionPerformed(evt);
            }
        });

        promptSuper6.setText("Enter a string that is a least 8 characters long. The program will output characters 4 to 6:");

        inputSuper8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSuper8ActionPerformed(evt);
            }
        });

        prompt4To6.setText("Characters 4 to 6");
        prompt4To6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prompt4To6ActionPerformed(evt);
            }
        });

        line1.setText("-----------------------------------------------------------------------------------------------------------------------------------------------------------------");

        line2.setText("-----------------------------------------------------------------------------------------------------------------------------------------------------------------");

        line3.setText("-----------------------------------------------------------------------------------------------------------------------------------------------------------------");

        line4.setText("-----------------------------------------------------------------------------------------------------------------------------------------------------------------");

        line5.setText("-----------------------------------------------------------------------------------------------------------------------------------------------------------------");

        line6.setText("-----------------------------------------------------------------------------------------------------------------------------------------------------------------");

        promptSuper7.setText("Enter a string that contains at least one \"a\". The program will then replace all occurence of the letter \"a\" with \"x\":");

        inputSuper9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSuper9ActionPerformed(evt);
            }
        });

        promptA.setText("Replaces \"a\"");
        promptA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promptAActionPerformed(evt);
            }
        });

        inputSuper4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSuper4ActionPerformed(evt);
            }
        });

        inputSuper7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSuper7ActionPerformed(evt);
            }
        });

        responseSuper1.setText("...");

        responseSuper2.setText("...");

        responseSuper3.setText("...");

        responseSuper4.setText("...");

        responseSuper5.setText("...");

        responseSuper6.setText("...");

        responseSuper7.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(line1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
            .addComponent(line2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(line3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(line4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(line5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(inputSuper2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(promptCaps)
                .addGap(115, 115, 115)
                .addComponent(responseSuper2)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(inputSuper3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(prompt4th)
                .addGap(117, 117, 117)
                .addComponent(responseSuper3)
                .addGap(45, 45, 45))
            .addComponent(line6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(inputSuper8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(prompt4To6)
                        .addGap(94, 94, 94)
                        .addComponent(responseSuper6)
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(promptSuper4)
                            .addComponent(promptSuper5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(inputSuper4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(inputSuper5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(84, 84, 84)
                                        .addComponent(promptIdentical))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(inputSuper6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(inputSuper7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(promtFound)
                                        .addGap(65, 65, 65)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(responseSuper4)
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(responseSuper5)
                                .addGap(43, 43, 43))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(promptSuper7)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(inputSuper9, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(promptA)
                                .addGap(103, 103, 103)
                                .addComponent(responseSuper7)
                                .addGap(14, 14, 14))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(promptSuper2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(titleSuper))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(promptSuper3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(promptSuper6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(promptSuper1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputSuper1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(214, 214, 214)
                                .addComponent(promptLength)
                                .addGap(113, 113, 113)))
                        .addComponent(responseSuper1)
                        .addGap(16, 16, 16)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleSuper)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(promptSuper1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(promptLength, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inputSuper1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(responseSuper1)))
                .addGap(3, 3, 3)
                .addComponent(line1)
                .addGap(1, 1, 1)
                .addComponent(promptSuper2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputSuper2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(promptCaps)
                    .addComponent(responseSuper2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line2)
                .addGap(1, 1, 1)
                .addComponent(promptSuper3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputSuper3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prompt4th)
                    .addComponent(responseSuper3))
                .addGap(2, 2, 2)
                .addComponent(line3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(promptSuper4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputSuper5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(promptIdentical)
                    .addComponent(inputSuper4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(responseSuper4))
                .addGap(3, 3, 3)
                .addComponent(line4)
                .addGap(1, 1, 1)
                .addComponent(promptSuper5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(promtFound, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inputSuper6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inputSuper7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(responseSuper5)))
                .addGap(2, 2, 2)
                .addComponent(line5)
                .addGap(2, 2, 2)
                .addComponent(promptSuper6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prompt4To6)
                    .addComponent(inputSuper8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(responseSuper6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line6)
                .addGap(2, 2, 2)
                .addComponent(promptSuper7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputSuper9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(promptA)
                    .addComponent(responseSuper7))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputSuper1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSuper1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSuper1ActionPerformed

    private void inputSuper2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSuper2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSuper2ActionPerformed

    private void inputSuper3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSuper3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSuper3ActionPerformed

    private void inputSuper5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSuper5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSuper5ActionPerformed

    private void inputSuper6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSuper6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSuper6ActionPerformed

    private void inputSuper8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSuper8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSuper8ActionPerformed

    private void inputSuper9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSuper9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSuper9ActionPerformed

    private void inputSuper4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSuper4ActionPerformed

    }//GEN-LAST:event_inputSuper4ActionPerformed

    private void inputSuper7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSuper7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSuper7ActionPerformed

    private void prompt4To6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prompt4To6ActionPerformed
        String answer8 = inputSuper8.getText();
        responseSuper6.setText("" + answer8.charAt(3) + answer8.charAt(4) + answer8.charAt(5));
    }//GEN-LAST:event_prompt4To6ActionPerformed

    private void promptLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promptLengthActionPerformed
        String answer1 = inputSuper1.getText();
        responseSuper1.setText("" + answer1.length());
    }//GEN-LAST:event_promptLengthActionPerformed

    private void promptCapsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promptCapsActionPerformed
        String answer2 = inputSuper2.getText();
        responseSuper2.setText("" + answer2.toUpperCase());
    }//GEN-LAST:event_promptCapsActionPerformed

    private void prompt4thActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prompt4thActionPerformed
        String answer3 = inputSuper3.getText();
        responseSuper3.setText("" + answer3.charAt(3));
    }//GEN-LAST:event_prompt4thActionPerformed

    private void promptIdenticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promptIdenticalActionPerformed
        String answer4 = inputSuper4.getText();
        String answer5 = inputSuper5.getText();
        if(answer4.equals(answer5)){
        responseSuper4.setText("Yes!");
        } else {
        responseSuper4.setText("No!");    
        }
    }//GEN-LAST:event_promptIdenticalActionPerformed

    private void promptAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promptAActionPerformed
        String answer9 = inputSuper9.getText();
        responseSuper7.setText("" + answer9.replace("a", "x"));
    }//GEN-LAST:event_promptAActionPerformed

    private void promtFoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promtFoundActionPerformed
        String answer6 = inputSuper6.getText();   
        String answer7 = inputSuper7.getText(); 
        if (answer6.contains​(answer7)){
        responseSuper5.setText("Yes!");
      }  else {
        responseSuper5.setText("No!");      
      }
    }//GEN-LAST:event_promtFoundActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(superString1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(superString1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(superString1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(superString1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new superString1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputSuper1;
    private javax.swing.JTextField inputSuper2;
    private javax.swing.JTextField inputSuper3;
    private javax.swing.JTextField inputSuper4;
    private javax.swing.JTextField inputSuper5;
    private javax.swing.JTextField inputSuper6;
    private javax.swing.JTextField inputSuper7;
    private javax.swing.JTextField inputSuper8;
    private javax.swing.JTextField inputSuper9;
    private javax.swing.JLabel line1;
    private javax.swing.JLabel line2;
    private javax.swing.JLabel line3;
    private javax.swing.JLabel line4;
    private javax.swing.JLabel line5;
    private javax.swing.JLabel line6;
    private javax.swing.JButton prompt4To6;
    private javax.swing.JButton prompt4th;
    private javax.swing.JButton promptA;
    private javax.swing.JButton promptCaps;
    private javax.swing.JButton promptIdentical;
    private javax.swing.JButton promptLength;
    private javax.swing.JLabel promptSuper1;
    private javax.swing.JLabel promptSuper2;
    private javax.swing.JLabel promptSuper3;
    private javax.swing.JLabel promptSuper4;
    private javax.swing.JLabel promptSuper5;
    private javax.swing.JLabel promptSuper6;
    private javax.swing.JLabel promptSuper7;
    private javax.swing.JButton promtFound;
    private javax.swing.JLabel responseSuper1;
    private javax.swing.JLabel responseSuper2;
    private javax.swing.JLabel responseSuper3;
    private javax.swing.JLabel responseSuper4;
    private javax.swing.JLabel responseSuper5;
    private javax.swing.JLabel responseSuper6;
    private javax.swing.JLabel responseSuper7;
    private javax.swing.JLabel titleSuper;
    // End of variables declaration//GEN-END:variables
}
